name: NodeBB QuickStart Plugin CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Pull latest source from GitHub repository
      run: |
          cd /home/ubuntu/nodebb/node_modules/nodebb-plugin-quickstart
          git remote -v
          git pull origin master
          cd /home/ubuntu/nodebb
          ./nodebb build
          ./nodebb restart
