name: NodeBB QuickStart Plugin

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    steps:          
     - name: Pull latest source for Quickstart Plugin
       run: |
        cd /home/ubuntu/nodebb/node_modules/nodebb-plugin-quickstart
        git pull origin master       

     - name: Install and restart NodeBB
       run: |
        cd /home/ubuntu/nodebb
        ./nodebb stop
         npm install nodebb-plugin-quickstart
        ./nodebb start
        ps -ef | grep nodebb
