name: NodeBB QuickStart Plugin

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Remove existing Quickstart Plugin directory
      run: rm -rf /home/ubuntu/nodebb/node_modules/nodebb-plugin-quickstart

    - name: Clone fresh source for Quickstart Plugin
      run: |
        git clone https://github.com/stelladream/nodebb-plugin-quickstart.git /home/ubuntu/nodebb/node_modules/nodebb-plugin-quickstart

    #- name: Rebuild and Restart NodeBB
    #  run: |
    #    cd /home/ubuntu/nodebb
    #    ./nodebb build
    #    ./nodebb restart
