name: NodeBB QuickStart Plugin

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Pull latest source for Quickstart Plugin
      run: |
        cd /home/ubuntu/nodebb/node_modules/nodebb-plugin-quickstart
        git pull origin master
        npm install

    - name: Rebuild and Restart NodeBB
      run: |
        cd /home/ubuntu/nodebb
        ./nodebb stop
        ./nodebb start
        ps -ef | grep nodebb
