name: NodeBB QuickStart Plugin

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    steps:          
     - name: Clone latest source for Quickstart Plugin
       run: |
        cd /home/ubuntu/nodebb/node_modules
        rm -rf nodebb-plugin-quickstart
        git clone https://github.com/stelladream/nodebb-plugin-quickstart.git

     - name: Install plugin and restart NodeBB
       run: |
        cd /home/ubuntu/nodebb
        ./nodebb stop
         npm install nodebb-plugin-quickstart
        nohup ./nodebb start &
        ps -ef | grep nodebb
